# Site settings
title: Nguyet Minh Duong
email: nguyetduong.minh@mail.com
description: A twenty year-old who loves to drink boba and talk about her life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mimiduong.me" # the base hostname & protocol for your site
twitter_username: sinnto
github_username:  nguyetduong

# Build settings
markdown: kramdown
